### ISSUE TITLE
NullPointerException handling multiple connections.

### ISSUE THREAD

**Issue by kikekr** [enilink/llrp4j#11]
Hi,
When I try to establish more than one simultaneous connection to my llrp server the NioHandler launches a NullPointerException with the next message:

```
Error while processing network channel
java.lang.NullPointerException
	at net.enilink.llrp4j.net.NioServer.run(NioServer.java:80)
	at java.lang.Thread.run(Thread.java:745)
```

With only one connection it works properly. Is your class 'LlrpServer' currently multithread?
This is my endpoint implementation:

```
LlrpEndpoint() {

	@Override
	public void errorOccured(String arg0, Throwable arg1) {
		System.err.println(arg0);
		System.err.println(arg1.getMessage());
		arg1.printStackTrace();
	}

	@Override
	public void messageReceived(LlrpMessage message) {
		String messageName = message.getClass().getSimpleName(); 
		Class<?> responseType = message.getResponseType();
		LlrpMessage response = handleMessage(message);
		if (response != null) {
			server.send(response);
		}
	}
};
```

**Comment by primeinterway** [comment]
Hi guys, I'm with the same issue. Is there any way around this?
